### ISSUE TITLE
Design report to include filtering, functionality and layout

### ISSUE THREAD

**Issue by uon-rcking** [99904047/DM3-Requirement-to-build-browser-report-to-display-correct-due-date#2]

**Comment by 99904047** [comment]
Karen

Has provided the following information:

Customer ID     apar_id
Customer Name   xapar_id
Sponsor ID  dim_5
InvoiceNo   ext_inv_ref
Inv.date    voucher_date
Gross Amount Inv    cur_amount
Amount Outstanding  rest_curr
VAT Amount (if any) 
Purchase Order Number  
Payment Plan    pay_plan_id
Notes   Indicator that notes exist ?
Transaction Type    xvoucher_type
Currency    currency
Student Type    Cat 6
Entity  Cat 7
Payment Due Date    due_date
Days overdue    f0_days_overdue
Current(not due yet)    f6_not_due_yet
0-13 Days  
14-28 Days Overdue  
29-42 Days  Overdue 
43-60 Days Overdue  
60 + Days Overdue   

Templates zipped up and sent today to DL and SJ
